// Team Names Database
// Generated: 2026-01-24T20:36:18.358Z

const teamNames = {
  "celestial": [
    "Andromeda Bound",
    "Apollo Crew",
    "Binary System",
    "Blue Moon Society",
    "Celestial Bodies",
    "Comet Chasers",
    "Constellation Crew",
    "Corona Crew",
    "Cosmic Ray Collective",
    "Crescent Moon Collective",
    "Dark Energy Crew",
    "Deep Space Nine",
    "Eclipse Collective",
    "Full Moon Society",
    "Galileo's Moons",
    "Gravity Wells",
    "Interstellar Collective",
    "Light Speed League",
    "Meteor Shower Crew",
    "New Moon Crew",
    "Night Sky Society",
    "Pioneer Society",
    "Planetarium Crew",
    "Quantum Collective",
    "Quasar Quartet",
    "Saturn's Rings",
    "Solar Flare Squad",
    "Solar Wind Society",
    "Spacetime Society",
    "Star Sailors",
    "Stardust Collective",
    "Stellar Nursery",
    "Supernova Syndicate",
    "Team Polaris",
    "The Asteroid Belt",
    "The Astral Projection",
    "The Astronomers",
    "The Astrophiles",
    "The Aurora Assembly",
    "The Big Dippers",
    "The Blueshifts",
    "The Cassinis",
    "The Celestials",
    "The Chromosphere",
    "The Copernicus Crew",
    "The Coronas",
    "The Cosmic Background",
    "The Cosmic Constants",
    "The Cosmic Drift",
    "The Cosmonauts",
    "The Cosmos Club",
    "The Dark Matter",
    "The Ecliptics",
    "The Equinox",
    "The Event Horizons",
    "The Final Frontier",
    "The Galactic Senate",
    "The Gas Giants",
    "The Harvest Moons",
    "The Heliosphere",
    "The Hubbles",
    "The Ice Giants",
    "The Ionosphere",
    "The Keplers",
    "The Kuiper Belt",
    "The Lunar League",
    "The Lunar Module",
    "The Lunar Tides",
    "The Magnetosphere",
    "The Main Sequence",
    "The Midnight Suns",
    "The Nadirs",
    "The Neutron Stars",
    "The Observatory",
    "The Oort Cloud",
    "The Orbiters",
    "The Parsecs",
    "The Photosphere",
    "The Pulsars",
    "The Redshifts",
    "The Rogue Planets",
    "The Shooting Stars",
    "The Singularities",
    "The Southern Cross",
    "The Space Cadets",
    "The Starfall Society",
    "The Stargazers",
    "The Telescopes",
    "The Void Walkers",
    "The Voyagers",
    "The Wormholes",
    "The Zeniths",
    "Umbra & Penumbra",
    "White Dwarf Collective"
  ],
  "mythology": [
    "Achilles Assembly",
    "Ambrosia Collective",
    "Apollo's Arrows",
    "Artemis Hunters",
    "Athena's Owls",
    "Atlas Society",
    "Calypso Crew",
    "Charon's Passengers",
    "Circe's Circle",
    "Delphi Society",
    "Demeter's Harvest",
    "Echo Collective",
    "Elysian Assembly",
    "Eos Assembly",
    "Helios Society",
    "Hera's Court",
    "Hercules League",
    "Hermes Wings",
    "Heroes of Old",
    "Hypnos Collective",
    "Icarus Society",
    "Midas Collective",
    "Morpheus Society",
    "Mount Olympus Crew",
    "Narcissus Society",
    "Nectar Society",
    "Odysseus Society",
    "Oracle Assembly",
    "Perseus Crew",
    "Phoenix Rising",
    "Prometheus Collective",
    "Selene Collective",
    "Sphinx Society",
    "Styx Crossers",
    "Tartarus Survivors",
    "Thanatos Society",
    "The Amazons",
    "The Argonauts",
    "The Athenians",
    "The Blessed Ones",
    "The Centaurs",
    "The Chimera Collective",
    "The Cursed Ones",
    "The Cyclopes",
    "The Daedalus Workshop",
    "The Dawn Bringers",
    "The Demigods",
    "The Dionysus Revel",
    "The Dream Weavers",
    "The Dryads",
    "The Dusk Walkers",
    "The Elysians",
    "The Epics",
    "The Fate Spinners",
    "The Fates",
    "The Ferryman's Crew",
    "The Forgemasters",
    "The Furies",
    "The Gorgons",
    "The Hydras",
    "The Immortals",
    "The Labyrinth Runners",
    "The Legacy",
    "The Legends",
    "The Lightning Bolts",
    "The Minotaurs",
    "The Muses",
    "The Mythmakers",
    "The Naiads",
    "The Nymphs",
    "The Oath Keepers",
    "The Olympians",
    "The Oracles",
    "The Prophets",
    "The Reapers",
    "The Riddlers",
    "The Satyrs",
    "The Shade Walkers",
    "The Shapeshifters",
    "The Sirens",
    "The Sleepwalkers",
    "The Spartans",
    "The Star Weavers",
    "The Thunderbolts",
    "The Titans",
    "The Trojans",
    "The Underworld Society",
    "The Vow Breakers",
    "The Wind Keepers",
    "Theseus Crew",
    "Titan Squad",
    "Trident Crew"
  ],
  "nature": [
    "Agents of Raccoon Chaos",
    "Ancient Oaks",
    "Apex Assembly",
    "Busy Honeybees",
    "Caffeinated Squirrels",
    "Canopy Dwellers",
    "Canyon Carvers",
    "Chirping Crickets",
    "Clever Orcas",
    "Clever Ravens",
    "Coastal Collective",
    "Coral Collective",
    "Crows With Grudges",
    "Dancing Dolphins",
    "Dawn Patrol",
    "Deep Current Collective",
    "Definitely Not Squirrels",
    "Delta Dwellers",
    "Driftwood Assembly",
    "Dusk Brigade",
    "Ecosystem of Bad Choices",
    "Feral But Functional",
    "Flamboyance of Flamingos",
    "Flickering Fireflies",
    "Flock Around and Find Out",
    "Forest Floor Society",
    "Geese With Intent",
    "Gentle Manatees",
    "Giant Sequoias",
    "Grumpy Grizzlies",
    "Here for Your Snacks",
    "High Tide Society",
    "Howling Wolves",
    "Kaleidoscope of Butterflies",
    "Lazy Sea Lions",
    "Leaping Salmon",
    "Lichen League",
    "Lonesome Loons",
    "Low Tide Collective",
    "Mighty Redwoods",
    "Migrating Monarchs",
    "Mischief of Mice",
    "Mostly Harmless Wildlife",
    "Murder of Crows",
    "Murmuration of Starlings",
    "Mycelium Collective",
    "Mysterious Narwhals",
    "Nocturnal and Unwell",
    "Nocturnal Assembly",
    "Northern Lights",
    "Old Growth",
    "One Opossum Short of a Problem",
    "Parliament of Owls",
    "Polar Bear Club",
    "Prairie Prowlers",
    "Pride of Lions",
    "Proper Penguins",
    "Quaking Aspens",
    "Ridge Riders",
    "River Runners",
    "Sandbar Society",
    "Scrappy Bobcats",
    "Several Possums in a Hoodie",
    "Shallow Creek Crew",
    "Singing Cicadas",
    "Skulk of Foxes",
    "Sleuth of Bears",
    "Sly Foxes",
    "Steady Herons",
    "Stealthy Mountain Lions",
    "Storm Chasers",
    "Stubborn Badgers",
    "Summit Seekers",
    "Sunbathing Seals",
    "Tall Pines",
    "Tangled Brambles",
    "The Audacity of Geese",
    "The Early Birds",
    "The Evergreens",
    "The Foragers",
    "The Hibernators",
    "The Invasive Species",
    "The Menacing Ducks",
    "The Migration",
    "The Night Owls",
    "The Pollinators",
    "The Saplings",
    "The Slightly Rabid",
    "The Suspicious Pigeons",
    "The Undertow",
    "The Unsupervised Geese",
    "The Untamed",
    "The Wildflowers",
    "The Wrongly Accused Foxes",
    "Thorny Thicket",
    "Three Raccoons in a Trenchcoat",
    "Thunder & Lightning",
    "Tidal Pool Explorers",
    "Towering Cedars",
    "Trailblazers United",
    "Treeline Tribe",
    "Unfurling Ferns",
    "Wandering Albatross",
    "Watershed Warriors",
    "We Bite If Provoked",
    "Wetland Warriors",
    "Whispering Willows",
    "Wilderness Wanderers",
    "Wildwood Society",
    "Wily Coyotes",
    "Wise Whales"
  ],
  "retro": [
    "Be Kind Rewind",
    "Bender's Detention",
    "Blockbuster Nights",
    "Bop It Champions",
    "Bratz Pack",
    "Bueller? Bueller?",
    "Butterfly Clips Society",
    "Club Penguin Veterans",
    "Double Rainbow",
    "Etch-A-Sketch Masters",
    "Groovy Girls",
    "Just Keep Swimming",
    "Keyboard Cat Society",
    "Life Moves Pretty Fast",
    "Lite-Brite Artists",
    "Mix CD Masters",
    "Monsters Inc",
    "Neopets Never Dies",
    "Never Gonna Give You Up",
    "No Capes Society",
    "Ogres Have Layers",
    "On Wednesdays We Wear Pink",
    "P. Sherman 42 Wallaby Way",
    "Pokemon Card Collectors",
    "Polly Pocket Society",
    "Potter Puppet Pals",
    "Put That Thing Back",
    "Rainbow Loom Society",
    "Scare Floor Society",
    "She Doesn't Even Go Here",
    "So Fetch Society",
    "Tamagotchi Survivors",
    "That's So Fetch",
    "The Bedazzlers",
    "The Blue Tangs",
    "The Breakfast Club",
    "The Burn Book",
    "The Dramatic Look",
    "The Easy-Bake Chefs",
    "The Furby Whisperers",
    "The Ghostbusters",
    "The Incredibles",
    "The Limit Does Not Exist",
    "The Llamas with Hats",
    "The Low Rise",
    "The Mysterious Ticking Noise",
    "The Plastics",
    "The Rickroll",
    "The Scream Collectors",
    "The Scrunchies",
    "The Skip-Its",
    "The Swamp Dwellers",
    "The Truffle Shuffle",
    "The Velociraptors",
    "The Wii Sports Pros",
    "VHS Collectors",
    "Where's My Super Suit",
    "You Go Glen Coco",
    "Yu-Gi-Oh Duelists"
  ],
  "food": [
    "Avocado Appreciation",
    "Birthday Cake Energy",
    "Brown Sugar Boba",
    "Brownie Edge Society",
    "Carb Loaders",
    "Cheese Board Society",
    "Cold Brew Crew",
    "Comfort Food Club",
    "Cookie Dough Society",
    "Crispy Edges Only",
    "Denny's at 2am",
    "Dino Nugget Enthusiasts",
    "Dunkin' Runs",
    "Emotional Support Beverage",
    "Everything Bagel",
    "Everything with Butter",
    "Extra Cheese Please",
    "Extra Ranch",
    "Fancy Lunchables",
    "Flamin' Hot Society",
    "Fruit Snack Hunters",
    "Funfetti Society",
    "Garlic Bread Gang",
    "Grilled Cheese Society",
    "Hot Dog Royalty",
    "Hot Sauce Everything",
    "Hydrate or Diedrate",
    "Instant Ramen Club",
    "Juice Box Society",
    "Loaded Nachos",
    "Lunchables Luxury",
    "Maruchan Enthusiasts",
    "Matcha Girlies",
    "Oat Milk Society",
    "Overly Complicated Orders",
    "Pizza Rats",
    "Prime Hydration",
    "Red Bull Reality",
    "Soft Center Club",
    "Sourdough Starters",
    "Sriracha Society",
    "Straight from the Oven",
    "Sweet & Salty",
    "Takis & Trauma",
    "Team Hangry",
    "The Avocado Toast",
    "The Banana Bread Era",
    "The Boba Addicts",
    "The Brunch Bunch",
    "The Burnt Toast",
    "The Capri Suns",
    "The Chicken Nuggets",
    "The Corner Piece",
    "The Customizers",
    "The Emotional Support Stanleys",
    "The Energy Drinks",
    "The Grazing Table",
    "The Guac is Extra",
    "The Hot Cheeto Girls",
    "The Iced Coffee",
    "The Jalapeño Poppers",
    "The Late Night Menu",
    "The Middle Piece",
    "The Midnight Snackers",
    "The Monster Energy",
    "The Mozzarella Sticks",
    "The Munchkins",
    "The Ramen Noodles",
    "The Secret Menu",
    "The Secret Sauce",
    "The Spice Squad",
    "The Sprinkles",
    "The Starbucks Order",
    "The Uncrustables",
    "The Warm Cookies",
    "The Water Bottles",
    "Waffle House Warriors"
  ],
  "music": [
    "Air Drum Society",
    "All Too Well Society",
    "Aux Privileges Revoked",
    "Better Than Original",
    "Binaural Beats",
    "Bonus Track Collective",
    "Brown Noise Believers",
    "Crying in the Car",
    "Deluxe Edition",
    "DJ Roommate",
    "Emotional Damage",
    "Encore Ensemble",
    "Friendship Bracelets",
    "General Admission",
    "Key Change Society",
    "Lip Sync Legends",
    "Living Rent Free",
    "Lofi Beats",
    "Main Character Soundtrack",
    "Main Stage Energy",
    "Misheard Lyrics Society",
    "Mosh Pit Energy",
    "One Song on Repeat",
    "Outro Energy",
    "Rain Sounds Society",
    "Red Light Concert",
    "Rhythm Section",
    "Spotify Wrapped",
    "Stuck in My Head",
    "Study Playlist Society",
    "The Algorithm Playlist",
    "The B-Sides",
    "The Bass Boosted",
    "The Beyhive",
    "The Cover Band",
    "The Deep Cuts",
    "The Front Row",
    "The Green Room",
    "The Headliners",
    "The Hidden Track",
    "The Hyperfixation Playlist",
    "The Intrusive Jingle",
    "The Leaked Album",
    "The Opening Act",
    "The Same Five Songs",
    "The Shower Singers",
    "The Steering Wheel Drums",
    "The Tortured Poets",
    "The Trending Page",
    "The Vault Tracks",
    "The Verified Fans",
    "Ticketmaster Victims",
    "Trade Bracelet Society",
    "Unreleased Demos",
    "Villain Arc Playlist",
    "Waiting for the Beat",
    "Waitlist Society",
    "Wrong Lyrics Confidence"
  ],
  "adventure": [
    "Accidental Adventurers",
    "Are We There Yet",
    "Backseat Navigators",
    "Carried by the Team",
    "Didn't Read the Instructions",
    "Didn't Sign Up for This",
    "Down the Rabbit Hole",
    "Finding the Way",
    "Forgot the Charger",
    "Going with the Flow",
    "Happy Accidents",
    "Here Be Dragons",
    "In Too Deep",
    "Into the Void",
    "Lost Luggage Society",
    "Main Character Journey",
    "Main Quest Avoiders",
    "Middle Seat Victims",
    "Missed the Exit",
    "No Plot Armor",
    "No Refunds",
    "No Service Society",
    "No Turning Back",
    "Not All Who Wander",
    "Not the Chosen One",
    "Not the Destination",
    "NPC Energy",
    "Off the Map",
    "Overpacked and Unbothered",
    "Personal Best Chasers",
    "Phone at One Percent",
    "Point of No Return",
    "Protagonist Problems",
    "Purposefully Lost",
    "Quest Accepted",
    "Ragtag Group",
    "Random Teammates",
    "Screenshot the Directions",
    "Send Location Society",
    "Shotgun Called",
    "Side Quest Society",
    "Sink or Swim Society",
    "Skill Issue Society",
    "Speed Run Society",
    "Squad Goals",
    "The Chosen Ones",
    "The Copilots",
    "The First Try",
    "The Found Family",
    "The Reluctant Hero",
    "The Side Characters",
    "The Trailblazers",
    "The Wanderers",
    "Took Several Tries",
    "Touched Grass Once",
    "Treading Water",
    "Tutorial Skippers",
    "Unlikely Heroes",
    "Upstream Swimmers",
    "Void Exploration Society",
    "Window Seat Society",
    "Wrong Protagonist",
    "Wrong Turn Takers"
  ],
  "cozy": [
    "Always Cold Club",
    "Antique Collectors",
    "Background Noise Society",
    "Blanket Burrito Society",
    "Bookmark Collectors",
    "Brain Dump Society",
    "Candle Hoarders",
    "Carbs as a Love Language",
    "Cardigan Collectors",
    "Cat Nap Society",
    "Chunky Knit Club",
    "Coffee First Society",
    "Comfort Movie Club",
    "Cottagecore Enthusiasts",
    "Couch Goblins",
    "Dog Ear Defenders",
    "Early to Bed Club",
    "Emotional Support Beverages",
    "Emotional Support Plushies",
    "Fell Asleep Watching",
    "Fireside Chat Club",
    "Five More Minutes",
    "Flashlight Under Covers",
    "Found Object Society",
    "Fountain Pen Society",
    "Frog Appreciators",
    "Fuzzy Sock Society",
    "Goblincore Collective",
    "Good Pen Only Club",
    "Grandma's Recipe Club",
    "Hands Wrapped Around Mug",
    "Heating Pad Club",
    "Hot People Walk Society",
    "Leaf Pressers",
    "Library Whispers",
    "Margin Scribblers",
    "Moss Collectors",
    "Mushroom Foragers",
    "Nature Table Curators",
    "One More Chapter",
    "Overdue Book Society",
    "Oversized Mug Society",
    "Overwatered and Underwatered",
    "Pillow Fort Architects",
    "Planner Addicts",
    "Plant Parents",
    "Pressed Flower Society",
    "Professional Nappers",
    "Quiet Hours Club",
    "Rainy Day Readers",
    "Reading Past Bedtime",
    "Shiny Rock Collectors",
    "Slipper Season",
    "Slow Morning Club",
    "Snooze Button Society",
    "Sourdough Starters",
    "Space Heater Society",
    "Squishmallow Society",
    "Sticker Collectors",
    "Stress Bakers",
    "Sunday Morning Society",
    "Sweater Weather Society",
    "Talking to Plants Society",
    "The Annotators",
    "The Autumn Enthusiasts",
    "The Bread Bakers",
    "The Comfort Reread",
    "The Garden Witches",
    "The Gentle Souls",
    "The Journalers",
    "The Late Risers",
    "The List Makers",
    "The Mug Collectors",
    "The Old Souls",
    "The Pebble Pockets",
    "The Sleep Enthusiasts",
    "The Stationary Lovers",
    "The Warm Blankets",
    "Thermostat Wars",
    "Thrift Store Regulars",
    "Too Many Books Club",
    "Too Many Plants Club",
    "Vintage Hunters",
    "Warm Cider Club",
    "Washi Tape Hoarders",
    "Wildflower Pickers",
    "Window Seat Enthusiasts"
  ],
  "chaos": [
    "3 AM Thoughts",
    "A Series of Poor Decisions",
    "Academic Weapons (Derogatory)",
    "And I Took That Personally",
    "Anxiety & Audacity",
    "Background Characters",
    "Beautiful Disasters",
    "Becoming the Villain",
    "Beige Flags Society",
    "Blue Screen of Death",
    "Bold of You to Assume",
    "Can't Stop Won't Stop",
    "Carrying the Group Chat",
    "Chaos Coordinators",
    "Chaotic Good Intentions",
    "Chaotic Neutral",
    "Chaotic Shipping",
    "Corrupted Files",
    "Crying in the Club",
    "Deadline Driven",
    "Deep in the Lore",
    "Delusion is the Solution",
    "Do Not Shake",
    "Don't Feed After Midnight",
    "Down the Rabbit Hole",
    "Due Tomorrow Do Tomorrow",
    "Error 404",
    "Everything is Fine",
    "Fafo Society",
    "Feral Creatures",
    "Feral Girl Summer",
    "Fight or Flight Society",
    "Flaming Trash Pile",
    "Fueled by Spite",
    "Future Me's Problem",
    "Gaslight Gatekeep Girlboss",
    "Girlboss Gone Wrong",
    "Goblin Mode Activated",
    "Gremlin Hours",
    "Handle with Chaos",
    "Have You Tried Turning It Off",
    "Hyperfixation Station",
    "I Simply Choose Violence",
    "I'm in Danger",
    "Left on Read Society",
    "Main Character Syndrome",
    "Manipulate Mansplain Malewife",
    "Menaces to Society",
    "No Sleep Schedule",
    "No Thoughts Head Empty",
    "No You Can't",
    "One Collective Brain Cell",
    "Organized Chaos",
    "Panic at the Deadline",
    "Please Restart",
    "Professional Overthinkers",
    "Raised by Wolves",
    "Rat Girl Summer",
    "Running on Caffeine",
    "Sad Girl Autumn",
    "Side Character Energy",
    "Still Not a Phase",
    "Task Failed Successfully",
    "That's a Problem for Later",
    "The Audacity",
    "The Black Sheep",
    "The Burning Building",
    "The Clowns",
    "The Consequences",
    "The Delulu",
    "The Doom Scrollers",
    "The Dumpster Fire",
    "The Entire Circus",
    "The Ghosted",
    "The Gremlins",
    "The Group Project Curse",
    "The Hot Mess Express",
    "The Intrusive Thoughts Won",
    "The Last Brain Cell",
    "The Last Minute",
    "The Lore Keepers",
    "The NPCs",
    "The Overthinkers Club",
    "The Plot Twist",
    "The Procrastinators",
    "The Red Flags",
    "The Roman Empire",
    "The Silly Geese",
    "The Sleep Deprived",
    "The Unhinged",
    "The Villain Era",
    "The Warning Label",
    "This is Fine",
    "Too Tired to Function",
    "Undomesticated",
    "Unhinged and Thriving",
    "Villain Origin Story",
    "Walking Icks",
    "We Can Fix Them"
  ],
  "cryptids": [
    "Ancient Aliens Society",
    "Area 51 Survivors",
    "Berenstain Truthers",
    "Bigfoot Believers",
    "Blurry Photo Society",
    "Chupacabra Chasers",
    "Could Be Anything",
    "Crop Circle Enthusiasts",
    "Cryptid Spotters",
    "Darkest Timeline",
    "Deep Sea Mysteries",
    "Drop Bear Believers",
    "Dust Particle Deniers",
    "Eyes on the Skies",
    "Ghost Hunters Society",
    "Glitch in the Matrix",
    "Healthy Skepticism Society",
    "Here Be Dragons",
    "Hidden Species Hunters",
    "It Was Aliens",
    "Keep Looking Up",
    "Lake Monster Enthusiasts",
    "Little Green Enthusiasts",
    "Loch Ness Loyalists",
    "Map Edge Explorers",
    "Megalodon Hopefuls",
    "Mysterious Disappearances",
    "Mysterious Patterns Society",
    "Needs More Evidence",
    "Night Sky Gazers",
    "Not Extinct Yet",
    "Ogopogo Society",
    "Out of Focus Society",
    "Paranormal Investigators",
    "Prove It Society",
    "Questions Only Society",
    "Sasquatch Squad",
    "Sea Serpent Spotters",
    "Something's Out There",
    "Squinting at Photos",
    "Still Looking",
    "Still Out There Society",
    "Stranger Things Happen",
    "Swamp Gas Deniers",
    "That's Clearly a Guy in a Suit",
    "The Believers",
    "The Champ Chasers",
    "The Curious",
    "The Jackalopes",
    "The Kraken Believers",
    "The Mothman Enthusiasts",
    "The Night Watch",
    "The Search Continues",
    "The Skeptics",
    "The Stargazers",
    "The Thylacine Truthers",
    "The Truth is Out There",
    "The Unexplainable",
    "The Urban Legends",
    "They Can't Stop All of Us",
    "Truth is Stranger Society",
    "UFO Spotters",
    "Unidentified Society",
    "Wrong Timeline Society",
    "Yeti Hunters"
  ],
  "literary": [],
  "local": [
    "50 Degrees is T-Shirt Weather",
    "Can't Feel My Face",
    "Coney Island Loyalists",
    "Dressed in Layers",
    "Euchre Champions",
    "Feels Like Negative Twenty",
    "Five Minutes Away",
    "Flip Flops in March",
    "Freshwater Ocean Believers",
    "Hot-N-Ready Generation",
    "It's Called Pop Society",
    "Lake Effect Survivors",
    "Leaving Now (Still Home)",
    "Meijer at Midnight",
    "Meijer Runs",
    "Michigan Left Survivors",
    "Midwest Nice",
    "No Yeah Definitely",
    "Ope Just Gonna Sneak Past",
    "Ope Society",
    "Point to Your Hand Society",
    "Pop Not Soda",
    "Pothole Dodgers",
    "Red Pop Enthusiasts",
    "Remote Learning Survivors",
    "Rock and Rye Society",
    "Roundabout Hesitaters",
    "Salt Truck Followers",
    "School Closing Watchers",
    "Sorry Not Sorry Society",
    "Still Wearing Shorts",
    "Strong Opinions on Coneys",
    "That's Different",
    "The Little Caesars",
    "The Snow Day Hopefuls",
    "The U-Turn Experts",
    "Vernors Believers",
    "Vernors for Stomachaches",
    "Windchill Ignorers",
    "Yeah No Society",
    "You're on Mute",
    "Zoom University Alumni"
  ],
  "internet": [
    "2 AM Scrolling",
    "Anxiety and Audacity",
    "Beautiful Disaster Club",
    "Brain Rot Society",
    "Caffeine and Anxiety",
    "Calendar Chaos",
    "Chronically Online",
    "Comment Section Survivors",
    "Deadline Driven",
    "Deep Dive Society",
    "Deep in the Comments",
    "Down the Rabbit Hole",
    "Due Tomorrow Society",
    "Embrace the Chaos",
    "Everything Happens Society",
    "Exceeded Expectations",
    "Fueled by Spite",
    "Future Me's Problem",
    "Good Enough Society",
    "Group Chat Chaos",
    "Head Empty Club",
    "How Did I Get Here",
    "Hyperfocus Mode",
    "It's Been Three Hours",
    "It's Giving Nothing",
    "Just One More Video",
    "Left on Read Society",
    "Living in My Head",
    "Main Character Energy",
    "Manifesting Energy",
    "Muted the Chat",
    "No Sleep Society",
    "No Thoughts Society",
    "NPC Behavior",
    "One Collective Brain Cell",
    "Organized Chaos Society",
    "Perfectionism Problems",
    "Phone Battery Anxiety",
    "Plot Armor Society",
    "Posted and Deleted",
    "Pressure Makes Diamonds",
    "Read at 2:47 AM",
    "Reading the Room",
    "Recovering People Pleasers",
    "Rent Free Living",
    "Running on Empty",
    "Screen Time Shamers",
    "Sensory Overload Society",
    "Side Character Society",
    "Skibidi Survivors",
    "That's Tomorrow's Issue",
    "The Background Characters",
    "The Blocked",
    "The Brain Cell",
    "The Brainworms",
    "The Doom Scrollers",
    "The Double Booked",
    "The Double Texters",
    "The Ghosted",
    "The Hot Mess",
    "The Last Minute",
    "The Lore Keepers",
    "The Lurkers",
    "The Mutuals",
    "The Overachievers",
    "The Overcommitted",
    "The Overthinkers",
    "The Procrastinators",
    "The Stan Account",
    "The Time Blindness",
    "The Vibe Check",
    "This is Fine Club",
    "Thriving (Allegedly)",
    "Too Many Group Chats",
    "Touched Grass Once",
    "Trust the Process",
    "Typing Bubble Watchers",
    "Unhinged in the Comments",
    "Up at 3 AM Society",
    "Where Did the Day Go",
    "Works Under Pressure"
  ]
};
